<?php declare(strict_types=1);

namespace Moorl\MerchantFinder;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\InstallContext;
use Shopware\Core\Framework\Plugin\Context\UninstallContext;

class MoorlMerchantFinder extends Plugin
{

    private static $_defaults = [
        'allowedSearchCountryCodes' => ['de', 'at', 'ch'],
        'nominatim' => 'https://nominatim.openstreetmap.org/search',
    ];

    public static function getDefault($key)
    {
        return self::$_defaults[$key];
    }

    public function install(InstallContext $installContext): void
    {
        parent::install($installContext); // TODO: Change the autogenerated stub
    }

    public function uninstall(UninstallContext $context): void
    {
        parent::uninstall($context);
        if ($context->keepUserData()) {
            return;
        }
        $connection = $this->container->get(Connection::class);
        $connection->executeQuery('DROP TABLE IF EXISTS `moorl_merchant_product_manufacturers`');
        $connection->executeQuery('DROP TABLE IF EXISTS `moorl_merchant_category`');
        $connection->executeQuery('DROP TABLE IF EXISTS `moorl_merchant_tag`');
        $connection->executeQuery('DROP TABLE IF EXISTS `moorl_merchant`');
        $connection->executeQuery('DROP TABLE IF EXISTS `moorl_zipcode`');
    }

    public function getStorefrontScriptPath(): string
    {
        return 'Resources/dist/storefront/js';
    }

}
