<?php declare(strict_types=1);

namespace Moorl\MerchantFinder;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\InstallContext;
use Shopware\Core\Framework\Plugin\Context\UninstallContext;
use MoorlFoundation\Core\PluginHelpers;

class MoorlMerchantFinder extends Plugin
{
    private static $_defaults = [
        'allowedSearchCountryCodes' => ['de', 'at', 'ch'],
        'nominatim' => 'https://nominatim.openstreetmap.org/search',
    ];

    public static function getDefault($key)
    {
        return static::$_defaults[$key];
    }

    public function install(InstallContext $installContext): void
    {
        parent::install($installContext); // TODO: Change the autogenerated stub
    }

    public function uninstall(UninstallContext $context): void
    {
        parent::uninstall($context);

        if ($context->keepUserData()) {
            return;
        }

        PluginHelpers::dropTables($this->container, $context->getContext(), [
            'moorl_merchant_tag',
            'moorl_merchant_category',
            'moorl_merchant_product_manufacturer',
            'moorl_merchant',
            'moorl_zipcode'
        ]);

        PluginHelpers::removeCmsBlocks($this->container, $context->getContext(), ['moorl-merchant-finder-basic']);
    }
}
